=== HoangLinh2001/SEM-2/XML/LAB/collection.dtd
<!ELEMENT collection (description,recipe*)>
<!ELEMENT description ANY> <!-- "Any" có thể có hoặc 0 có giá trị  -->
<!ELEMENT recipe (title,ingredient*,preparation,comment?,nutrition)> 
<!ELEMENT title (#PCDATA)> <!-- kiểu dữ liệu chuỗi -->
<!ELEMENT ingredient (ingredient*,preparation)?> 
<!ATTLIST ingredient 
    name CDATA #REQUIRED 
    amount CDATA #IMPLIED
    unit CDATA #IMPLIED> 
<!--
"#REQUIRED" dữ liệu bắt buộc phải có
#IMPLIED dữ liệu có hoặc không đều được
-->
<!ELEMENT preparation (step*)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT nutrition EMPTY>
<!ATTLIST nutrition 
    protein CDATA #REQUIRED 
    carbohydrates CDATA #REQUIRED 
    fat CDATA #REQUIRED 
    calories CDATA #REQUIRED 
    alcohol CDATA #IMPLIED>

=== HoangLinh2001/SEM-2/XML/LAB/collection.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collection SYSTEM "collection.dtd">

<collection>
    <description></description>
    <recipe>
    <title>Eat clean</title>
    <ingredient name="fruit">
        <ingredient name="banana"></ingredient>
        <preparation>
        <step>go to market</step>
        <step>buy banana</step>
        </preparation>
    </ingredient>
    <preparation>
        <step>peel banana</step>
        <step>eat</step>
    </preparation>
    <comment>Do not eat peel banana</comment>
    <nutrition protein="" carbohydrates="" fat="" calories=""/>
</recipe>
</collection>
